name: Test, Build and Publish

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:
    inputs:
      skip_tests:
        description: 'Skip tests (not allowed by everyone)'
        type: boolean
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org/'
          scope: '@webpros'

      - name: Install Dependencies
        working-directory: ./src
        run: npm ci

      - name: Run JEST tests
        working-directory: ./src
        env:
          TEST_USERNAME: ${{ secrets.TEST_USERNAME }}
          TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}
        run: npm run test
        if: ${{ github.event_name != 'workflow_dispatch' || (!github.event.inputs.skip_tests || github.triggering_actor != 'malteschlueter') }}

      - run: npm run prePublish

      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
